-- ================================================================
-- StreetRise — Migration 061: expand verified Florida second-chance housing
-- Data-only seed. Sources checked 2026-09-05.
--
-- Second Chance remains a derived search, not a resource type:
--   population_focus contains 'reentry' OR accepts_felony = true.
-- Unknown criminal-history answers stay NULL.
-- Correctional/BOP placements are marked requires_referral = true.
-- ================================================================

-- Providers -------------------------------------------------------
INSERT INTO providers (
  organization_name, contact_name, contact_email, contact_phone, website,
  verification_status, identity_confirmed, claim_status, source_type,
  external_id, last_imported_at, last_verified_at, verification_notes
)
VALUES
('Abe Brown Ministries','inspHire Intake','info@abebrown.org','813-247-3285','https://abebrown.org/','verified',FALSE,'unclaimed','seeded','housing-provider-abe-brown',now(),now(),'Official inspHire housing/intake pages checked 2026-09-05.'),
('Inner Strength Living','Housing Intake','Help@innerstrengthliving.com','813-296-6210','https://innerstrengthliving.com/','verified',FALSE,'unclaimed','seeded','housing-provider-inner-strength',now(),now(),'Official reentry housing/admissions pages checked 2026-09-05.'),
('70x7 Housing Foundation Inc','Housing Intake','info@70x7housing.org','813-727-7076','https://70x7housing.org/','verified',FALSE,'unclaimed','seeded','housing-provider-70x7',now(),now(),'Official justice-involved housing/application pages checked 2026-09-05.'),
('Timothy Initiative Ministries Inc','Program Intake','info@TimothyInitiative.org','813-843-3645','https://timothyinitiative.org/','verified',FALSE,'unclaimed','seeded','housing-provider-timothy-initiative',now(),now(),'Official current residential restoration and intake pages checked 2026-09-05.'),
('Project 180','Antonia Rolle','antonia@project180reentry.org','941-780-5227','https://www.project180reentry.org/','verified',FALSE,'unclaimed','seeded','housing-provider-project-180',now(),now(),'Official Residential Program/contact pages checked 2026-09-05.'),
('Angels of Mercy Ministries','Aura Lynn-Rouse','auralynn@angelsofmercyministries.org','321-696-9850','https://angelsofmercyministries.org/','verified',FALSE,'unclaimed','seeded','housing-provider-angels-mercy',now(),now(),'Official bridge-housing site and 2025 program/application material checked 2026-09-05.'),
('Reign of Hope Inc','Housing Intake','contact@reignofhope.org','407-848-0617','https://reignofhope.org/','verified',FALSE,'unclaimed','seeded','housing-provider-reign-hope',now(),now(),'Official Second Chance/Reentry Housing pages checked 2026-09-05.'),
('Open Homes Fellowship','Program Intake','info@openhomesfellowship.com','407-382-7962','https://openhomesfellowship.org/','verified',FALSE,'unclaimed','seeded','housing-provider-open-homes',now(),now(),'Official residential program, intake and contact pages checked 2026-09-05.'),
('Operation New Hope','Ready4Work Orlando','info@operationnewhope.org','321-234-4782','https://operationnewhope.org/','verified',FALSE,'unclaimed','seeded','housing-provider-operation-new-hope',now(),now(),'Official Orlando Ready4Work and statewide network pages checked 2026-09-05.'),
('The Lord''s Place','Vanessa Klein','VKlein@TheLordsPlace.org','561-467-6874','https://thelordsplace.org/','verified',FALSE,'unclaimed','seeded','housing-provider-lords-place',now(),now(),'Official Palm Beach County reentry page checked 2026-09-05.'),
('Riverside House','Reentry Program','info@riverside-house.org','305-326-9799','https://riversidehouse.org/','verified',FALSE,'unclaimed','seeded','housing-provider-riverside-house',now(),now(),'Official residential-reentry, FAQ, facility and contact pages checked 2026-09-05.'),
('Banyan Community Health','Behavioral Health','helpdesk@banyanhealth.org','305-774-3300','https://banyanhealth.org/','verified',FALSE,'unclaimed','seeded','housing-provider-banyan',now(),now(),'Official residential RRC page and federal BOP directory checked 2026-09-05; public resource uses the RRC phone, not this administrative email.'),
('Restoration Destination','Matthew Lavin','info@restorationdestination.org','561-924-5556','https://restorationdestination.org/','verified',FALSE,'unclaimed','seeded','housing-provider-restoration-destination',now(),now(),'Official reentry housing pages and current 211 record checked 2026-09-05.'),
('Fern House Inc','Residential Intake','info@fernhouse.org','561-471-0430','https://fernhouse.org/','verified',FALSE,'unclaimed','seeded','housing-provider-fern-house',now(),now(),'Official residential rehabilitation/transitional-living page checked 2026-09-05.')
ON CONFLICT (external_id) WHERE external_id IS NOT NULL DO UPDATE SET
 organization_name=EXCLUDED.organization_name, contact_name=EXCLUDED.contact_name,
 contact_email=EXCLUDED.contact_email, contact_phone=EXCLUDED.contact_phone,
 website=EXCLUDED.website, verification_status=EXCLUDED.verification_status,
 identity_confirmed=EXCLUDED.identity_confirmed, claim_status=EXCLUDED.claim_status,
 source_type=EXCLUDED.source_type, last_imported_at=EXCLUDED.last_imported_at,
 last_verified_at=EXCLUDED.last_verified_at, verification_notes=EXCLUDED.verification_notes,
 updated_at=now();

-- Resources -------------------------------------------------------
WITH seed(provider_external_id,external_id,name,description,resource_type,address,phone,email,website,availability_status,access_type,requires_referral,requires_id,gender_policy,population_focus,confidence_score,verification_notes) AS (
VALUES
('housing-provider-abe-brown','housing-abe-brown-insphire','Abe Brown Ministries — inspHire Transitional Housing','Transitional housing support for eligible inspHire participants rebuilding after incarceration or justice-system involvement. The 12-month program combines housing stability with professional development, employment assistance, coaching and transportation support.','transitional_housing','{"street":"2921 N 29th Street","city":"Tampa","state":"FL","zip":"33605"}'::jsonb,'813-247-3285','info@abebrown.org','https://abebrown.org/insphire-become-a-client/','unknown'::availability_status,'phone_intake'::resource_access_type,FALSE,TRUE,'gender_inclusive',ARRAY['reentry']::text[],98::smallint,'Housing is for enrolled inspHire participants. Official eligibility excludes sexual-offense convictions and generally excludes habitual violent offenders, with some circumstances reviewed individually.'),
('housing-provider-inner-strength','housing-inner-strength-reentry','Inner Strength Living — Reentry Housing','Shared, structured housing across Tampa Bay for people seeking a fresh start, including individuals re-entering society. Homes are furnished and drug- and alcohol-free.','shared_housing','{"city":"Tampa Bay","state":"FL"}'::jsonb,'813-296-6210','Help@innerstrengthliving.com','https://innerstrengthliving.com/','unknown'::availability_status,'web_intake'::resource_access_type,FALSE,TRUE,'gender_inclusive',ARRAY['reentry']::text[],95::smallint,'Official site explicitly offers a Re-entry Program. Exact residence is assigned after intake.'),
('housing-provider-70x7','housing-70x7-justice-involved','70x7 Housing Foundation — Justice-Involved Shared Housing','Drug- and alcohol-free shared housing in the Tampa Bay area for vulnerable adults, including justice-involved people and returning citizens.','shared_housing','{"city":"Tampa Bay","state":"FL"}'::jsonb,'813-727-7076','info@70x7housing.org','https://70x7housing.org/','unknown'::availability_status,'web_intake'::resource_access_type,FALSE,FALSE,'gender_inclusive',ARRAY['reentry']::text[],95::smallint,'Official site identifies justice-involved/returning citizens among populations served.'),
('housing-provider-timothy-initiative','housing-timothy-initiative-restoration','Timothy Initiative — Residential Restoration & Journey Homes','Year-long Christ-centered residential restoration for men rebuilding after addiction, incarceration, homelessness or other major life disruption. The pathway includes recovery homes, work therapy and transition toward independent living.','recovery_residence','{"street":"3309 N 15th Street","city":"Tampa","state":"FL","zip":"33605"}'::jsonb,'813-843-3645','info@TimothyInitiative.org','https://timothyinitiative.org/','unknown'::availability_status,'web_intake'::resource_access_type,FALSE,FALSE,'men_only',ARRAY['reentry']::text[],97::smallint,'Official current program explicitly includes men rebuilding after incarceration.'),
('housing-provider-project-180','housing-project-180-residential','Project 180 — Residential Program','Long-term residential reentry program in Sarasota for formerly incarcerated men in active recovery, including stable residency, food, clothing, transportation, employment assistance and other reentry support.','transitional_housing','{"city":"Sarasota","state":"FL"}'::jsonb,'941-780-5227','antonia@project180reentry.org','https://www.project180reentry.org/portfolio-item/residential-program/','unknown'::availability_status,'phone_intake'::resource_access_type,TRUE,FALSE,'men_only',ARRAY['reentry']::text[],98::smallint,'Official program offers up to two years of residency; candidates are interviewed and may be vetted by justice-system partners.'),
('housing-provider-angels-mercy','housing-angels-mercy-tarp','Angels of Mercy Ministries — Angels Restoration Place','Bridge and transitional housing for women reentering society after incarceration, homelessness, addiction or related displacement, with counseling, mentoring, recovery structure and employment support.','transitional_housing','{"city":"Sanford","state":"FL"}'::jsonb,'321-696-9850','auralynn@angelsofmercyministries.org','https://angelsofmercyministries.org/','unknown'::availability_status,'web_intake'::resource_access_type,FALSE,FALSE,'women_only',ARRAY['reentry']::text[],98::smallint,'2025 program material says participants are triaged regardless of criminal history, credit or past evictions.'),
('housing-provider-reign-hope','housing-reign-hope-reentry','Reign of Hope — Second Chance Reentry Housing','Shared and independent second-chance housing across Central Florida. Reentry Housing is designed for non-violent offenders rebuilding after incarceration.','shared_housing','{"state":"FL"}'::jsonb,'407-848-0617','contact@reignofhope.org','https://reignofhope.org/','unknown'::availability_status,'web_intake'::resource_access_type,FALSE,FALSE,'gender_inclusive',ARRAY['reentry']::text[],93::smallint,'Official site explicitly labels the program Second Chance Housing and Reentry Housing for non-violent offenders.'),
('housing-provider-open-homes','housing-open-homes-regeneration','Open Homes Fellowship — Regeneration Residential Program','Christian residential program for adult men addressing addiction and life-controlling issues. Open Homes has a pre-release intake path for applicants who are still incarcerated.','recovery_residence','{"street":"1831 Central Park Ave","city":"Orlando","state":"FL","zip":"32807"}'::jsonb,'407-382-7962','info@openhomesfellowship.com','https://openhomesfellowship.org/intake/','unknown'::availability_status,'phone_intake'::resource_access_type,FALSE,TRUE,'men_only',ARRAY['reentry']::text[],95::smallint,'Official intake page allows incarcerated applicants to be considered through coordination with a judicial representative.'),
('housing-provider-operation-new-hope','housing-operation-new-hope-orlando','Operation New Hope — Orlando Reentry Housing Support','Ready4Work Orlando support for justice-impacted people includes case management and transitional-housing assistance alongside employment, mental-health, transportation and stabilization services.','housing_navigation','{"street":"3815 E Colonial Drive","city":"Orlando","state":"FL","zip":"32803"}'::jsonb,'321-234-4782','info@operationnewhope.org','https://operationnewhope.org/ready4work-orlando/','unknown'::availability_status,'web_intake'::resource_access_type,FALSE,FALSE,'gender_inclusive',ARRAY['reentry']::text[],95::smallint,'Classified as housing navigation/support rather than a promise of a bed at the office.'),
('housing-provider-lords-place','housing-lords-place-reentry-navigation','The Lord''s Place — Reentry Housing Navigation','Housing navigation and wraparound reentry support for eligible people convicted in and returning to Palm Beach County, including housing referrals, employment, treatment, identification and benefits assistance.','housing_navigation','{"street":"2808 N Australian Ave","city":"West Palm Beach","state":"FL","zip":"33407"}'::jsonb,'561-467-6874','VKlein@TheLordsPlace.org','https://thelordsplace.org/what-we-do/reentry-program/','unknown'::availability_status,'phone_intake'::resource_access_type,TRUE,FALSE,'gender_inclusive',ARRAY['reentry']::text[],98::smallint,'Provider explicitly says its Reentry Program is not itself internal housing; this record represents housing navigation.'),
('housing-provider-riverside-house','housing-riverside-house-rrc','Riverside House — Residential Reentry Program','Structured residential reentry in Miami for men and women transitioning from incarceration, with supervised housing, meals, case management, employment preparation, counseling and transition planning.','transitional_housing','{"street":"968 NW 2nd Street","city":"Miami","state":"FL","zip":"33128"}'::jsonb,'305-326-9799','info@riverside-house.org','https://riversidehouse.org/programs/residential-reentry/','unknown'::availability_status,'phone_intake'::resource_access_type,TRUE,FALSE,'gender_inclusive',ARRAY['reentry']::text[],99::smallint,'Residential placement is through BOP or other authorized federal supervision partners; not public walk-in rental housing.'),
('housing-provider-banyan','housing-banyan-rrc-miami','Banyan Community Health — Residential Reentry Center','Bureau of Prisons residential reentry center in Miami providing structured, supervised housing and access to health care, employment counseling, job placement and reintegration support for people nearing release.','transitional_housing','{"street":"120 NW 59th Street","city":"Miami","state":"FL","zip":"33127"}'::jsonb,'305-398-6127',NULL,'https://banyanhealth.org/behavioral-health/adult-psychiatric/behavioral-health-centers/','unknown'::availability_status,'phone_intake'::resource_access_type,TRUE,FALSE,'gender_inclusive',ARRAY['reentry']::text[],99::smallint,'Correctional/federal referral placement; not open public rental housing.'),
('housing-provider-restoration-destination','housing-restoration-destination-reentry','Restoration Destination — Reentry Housing','Transitional and permanent shared housing in Pahokee for people rebuilding after incarceration, with transportation, probation/registration support, employment assistance and other reentry services.','shared_housing','{"street":"120 Pelican Lake Drive","city":"Pahokee","state":"FL","zip":"33476"}'::jsonb,'561-924-5556','info@restorationdestination.org','https://restorationdestination.org/prison-reentry-housing/','unknown'::availability_status,'phone_intake'::resource_access_type,FALSE,FALSE,'gender_inclusive',ARRAY['reentry']::text[],98::smallint,'Official site plus 211 Palm Beach/Treasure Coast record updated 2026-04-29 checked. 211 lists first-time non-violent offenders case-by-case and states the agency is compliant to house sex offenders.'),
('housing-provider-fern-house','housing-fern-house-reentry-recovery','Fern House — Residential Recovery & Transitional Living','Structured residential rehabilitation and transitional living for men affected by chronic alcohol/drug addiction, including formerly incarcerated and homeless men.','recovery_residence','{"street":"1958 Church Street","city":"West Palm Beach","state":"FL","zip":"33409"}'::jsonb,'561-471-0430','info@fernhouse.org','https://fernhouse.org/mission/','unknown'::availability_status,'phone_intake'::resource_access_type,FALSE,FALSE,'men_only',ARRAY['reentry']::text[],98::smallint,'Official page explicitly identifies formerly incarcerated men among the population served.')
)
INSERT INTO resources (
 provider_id,name,description,category,resource_type,address,phone,email,website,
 availability_status,verification_status,is_active,walk_ins_accepted,requires_id,
 requires_referral,access_type,is_map_ready,gender_policy,population_focus,
 external_id,source_file,import_batch_id,last_imported_at,last_verified_at,
 confidence_score,stale_after_days,verification_notes
)
SELECT p.id,s.name,s.description,'housing'::resource_category,s.resource_type,s.address,
 s.phone,s.email,s.website,s.availability_status,'verified'::verification_status,TRUE,FALSE,
 s.requires_id,s.requires_referral,s.access_type,FALSE,s.gender_policy,s.population_focus,
 s.external_id,'migration_061','housing_second_chance_061',now(),now(),s.confidence_score,30,s.verification_notes
FROM seed s JOIN providers p ON p.external_id=s.provider_external_id
ON CONFLICT (external_id) WHERE external_id IS NOT NULL DO UPDATE SET
 provider_id=EXCLUDED.provider_id,name=EXCLUDED.name,description=EXCLUDED.description,
 category=EXCLUDED.category,resource_type=EXCLUDED.resource_type,address=EXCLUDED.address,
 phone=EXCLUDED.phone,email=EXCLUDED.email,website=EXCLUDED.website,
 availability_status=EXCLUDED.availability_status,verification_status=EXCLUDED.verification_status,
 is_active=EXCLUDED.is_active,walk_ins_accepted=EXCLUDED.walk_ins_accepted,
 requires_id=EXCLUDED.requires_id,requires_referral=EXCLUDED.requires_referral,
 access_type=EXCLUDED.access_type,is_map_ready=EXCLUDED.is_map_ready,
 gender_policy=EXCLUDED.gender_policy,population_focus=EXCLUDED.population_focus,
 source_file=EXCLUDED.source_file,import_batch_id=EXCLUDED.import_batch_id,
 last_imported_at=EXCLUDED.last_imported_at,last_verified_at=EXCLUDED.last_verified_at,
 confidence_score=EXCLUDED.confidence_score,stale_after_days=EXCLUDED.stale_after_days,
 verification_notes=EXCLUDED.verification_notes,updated_at=now();

-- Housing details -------------------------------------------------
WITH d(external_id,accepts_felony,accepts_violent_offense,accepts_sex_offense,requires_sobriety,has_curfew,minimum_monthly_cost_cents,deposit_cents,max_stay_days,application_url,intake_phone,eligibility_notes) AS (
VALUES
('housing-abe-brown-insphire',TRUE,NULL::boolean,FALSE,TRUE,NULL::boolean,NULL::integer,NULL::integer,365,'https://abebrown.org/insphire-become-a-client/','813-247-3285','18+ with justice-system/lived incarceration experience; returning to Hillsborough, Pinellas, Pasco or Polk; drug-free and able to work full time. No sexual-offense convictions. Habitual violent-offender classification generally excluded, with some circumstances reviewed individually.'),
('housing-inner-strength-reentry',NULL::boolean,NULL::boolean,NULL::boolean,TRUE,NULL::boolean,NULL::integer,NULL::integer,NULL::integer,'https://innerstrengthliving.com/','813-296-6210','Requires photo ID, at least 30 days sober and agreement to house rules. No credit check. Specific offense exclusions are not stated.'),
('housing-70x7-justice-involved',NULL::boolean,NULL::boolean,NULL::boolean,TRUE,NULL::boolean,76000,25000,NULL::integer,'https://70x7housing.org/apply/','813-727-7076','Justice-involved/returning citizens are explicitly served. Drug/alcohol-free; drug-free test at move-in. Published cost is $190/week or $760/month plus a one-time $250 program fee.'),
('housing-timothy-initiative-restoration',NULL::boolean,NULL::boolean,NULL::boolean,NULL::boolean,NULL::boolean,NULL::integer,NULL::integer,365,'https://timothyinitiative.org/','813-843-3645','Men rebuilding after incarceration are explicitly eligible to apply. Year-long structured Christ-centered residential pathway. Specific offense exclusions are not published.'),
('housing-project-180-residential',TRUE,NULL::boolean,FALSE,TRUE,NULL::boolean,NULL::integer,NULL::integer,730,'https://www.project180reentry.org/about-us/contact-us/','941-780-5227','Formerly incarcerated men in active recovery; up to two years. Provider states it does not knowingly admit people with a crime against a child, sex crime or arson history; other restrictions are reviewed during intake.'),
('housing-angels-mercy-tarp',TRUE,NULL::boolean,NULL::boolean,TRUE,NULL::boolean,NULL::integer,NULL::integer,548,'https://angelsofmercyministries.org/wp-content/uploads/2025/07/AOM-Brouchure-and-Application-Corrected-2025-V3.pdf','321-696-9850','Women reentering from prison, jail or rehab. 2025 material says triage regardless of criminal history, credit or past evictions. Applicants must be 30 days clean/sober. Program described as 6–18 months; $300 entrance fee and $175 weekly rent.'),
('housing-reign-hope-reentry',TRUE,FALSE,NULL::boolean,NULL::boolean,NULL::boolean,NULL::integer,NULL::integer,NULL::integer,'https://reignofhope.org/apply-housing','407-848-0617','Official program description says Reentry Housing is for non-violent offenders rebuilding after incarceration. Sex-offense eligibility is not separately stated.'),
('housing-open-homes-regeneration',NULL::boolean,NULL::boolean,NULL::boolean,TRUE,NULL::boolean,NULL::integer,NULL::integer,NULL::integer,'https://openhomesfellowship.org/intake/','407-382-7962','Adult men; drug/alcohol-free at least 72 hours before face-to-face interview and urine test. Incarcerated applicants can be evaluated with a judicial representative. Specific offense exclusions are not stated.'),
('housing-operation-new-hope-orlando',NULL::boolean,NULL::boolean,NULL::boolean,NULL::boolean,NULL::boolean,NULL::integer,NULL::integer,NULL::integer,'https://operationnewhope.org/apply-for-our-program/','321-234-4782','Ready4Work serves justice-impacted people and lists transitional housing among Orlando support services. Housing navigation/support only; office is not represented as a residence.'),
('housing-lords-place-reentry-navigation',NULL::boolean,NULL::boolean,NULL::boolean,NULL::boolean,NULL::boolean,NULL::integer,NULL::integer,NULL::integer,'https://thelordsplace.org/what-we-do/reentry-program/','561-467-6874','For people involved with the Palm Beach County justice system; includes housing navigation/referrals. Provider explicitly says Reentry is not an internal housing program.'),
('housing-riverside-house-rrc',NULL::boolean,NULL::boolean,NULL::boolean,NULL::boolean,TRUE,NULL::integer,NULL::integer,NULL::integer,'https://riversidehouse.org/programs/residential-reentry/','305-326-9799','Placement through BOP/authorized federal supervision partners; no direct public residential application. Residents follow schedules and curfews. Co-ed with separated living areas.'),
('housing-banyan-rrc-miami',NULL::boolean,NULL::boolean,NULL::boolean,NULL::boolean,NULL::boolean,NULL::integer,NULL::integer,NULL::integer,'https://banyanhealth.org/behavioral-health/adult-psychiatric/behavioral-health-centers/','305-398-6127','Residential Reentry Center operated with the Federal Bureau of Prisons for people nearing release. Placement is correctional/federal referral.'),
('housing-restoration-destination-reentry',TRUE,FALSE,TRUE,TRUE,NULL::boolean,90000,NULL::integer,NULL::integer,'https://restorationdestination.org/prison-reentry-housing/','561-924-5556','Direct reentry housing. Current 211 record lists first-time non-violent offenders case-by-case, $900/month plus $400 administrative fee, and states the agency is compliant with state/county guidelines to house sex offenders.'),
('housing-fern-house-reentry-recovery',NULL::boolean,NULL::boolean,NULL::boolean,TRUE,NULL::boolean,NULL::integer,NULL::integer,NULL::integer,'https://fernhouse.org/mission/','561-471-0430','Drug/alcohol-free residential recovery for men; provider explicitly serves formerly incarcerated men. Fern House II provides longer-term transitional living after the primary recovery program. Specific offense exclusions are not stated.')
)
INSERT INTO resource_housing_details (
 resource_id,accepts_felony,accepts_violent_offense,accepts_sex_offense,
 requires_sobriety,has_curfew,minimum_monthly_cost_cents,deposit_cents,max_stay_days,
 application_url,intake_phone,eligibility_notes,housing_details_last_checked_at
)
SELECT r.id,d.accepts_felony,d.accepts_violent_offense,d.accepts_sex_offense,
 d.requires_sobriety,d.has_curfew,d.minimum_monthly_cost_cents,d.deposit_cents,d.max_stay_days,
 d.application_url,d.intake_phone,d.eligibility_notes,now()
FROM d JOIN resources r ON r.external_id=d.external_id
ON CONFLICT (resource_id) DO UPDATE SET
 accepts_felony=EXCLUDED.accepts_felony,accepts_violent_offense=EXCLUDED.accepts_violent_offense,
 accepts_sex_offense=EXCLUDED.accepts_sex_offense,requires_sobriety=EXCLUDED.requires_sobriety,
 has_curfew=EXCLUDED.has_curfew,minimum_monthly_cost_cents=EXCLUDED.minimum_monthly_cost_cents,
 deposit_cents=EXCLUDED.deposit_cents,max_stay_days=EXCLUDED.max_stay_days,
 application_url=EXCLUDED.application_url,intake_phone=EXCLUDED.intake_phone,
 eligibility_notes=EXCLUDED.eligibility_notes,housing_details_last_checked_at=EXCLUDED.housing_details_last_checked_at,
 updated_at=now();

-- Evidence --------------------------------------------------------
WITH ev(external_id,claim_field,method,outcome,source_url,source_name,notes) AS (
VALUES
('housing-abe-brown-insphire','population_focus.reentry','official_website','confirmed','https://abebrown.org/insphire-become-a-client/','Abe Brown Ministries','Justice-system/lived incarceration experience is an eligibility path and transitional housing is provided to participants.'),
('housing-abe-brown-insphire','accepts_sex_offense','official_website','not_eligible','https://abebrown.org/insphire-become-a-client/','Abe Brown Ministries','Official eligibility says no sexual-offense convictions.'),
('housing-inner-strength-reentry','population_focus.reentry','official_website','confirmed','https://innerstrengthliving.com/','Inner Strength Living','Official site lists a Re-entry Program and housing for people re-entering society.'),
('housing-70x7-justice-involved','population_focus.reentry','official_website','confirmed','https://70x7housing.org/','70x7 Housing Foundation Inc','Official site identifies justice-involved/returning citizens among populations served.'),
('housing-timothy-initiative-restoration','population_focus.reentry','official_website','confirmed','https://timothyinitiative.org/','Timothy Initiative Ministries Inc','Official program explicitly includes men rebuilding after incarceration and describes a residential pathway.'),
('housing-project-180-residential','population_focus.reentry','official_website','confirmed','https://www.project180reentry.org/portfolio-item/residential-program/','Project 180','Residential Program is for formerly incarcerated men and provides up to two years of residency.'),
('housing-project-180-residential','accepts_sex_offense','official_website','not_eligible','https://www.project180reentry.org/portfolio-item/residential-program/','Project 180','Official page says no individual is knowingly admitted with a sex-crime history.'),
('housing-angels-mercy-tarp','accepts_felony','official_program_document','confirmed','https://angelsofmercyministries.org/wp-content/uploads/2025/07/AOM-Brouchure-and-Application-Corrected-2025-V3.pdf','Angels of Mercy Ministries','2025 material says triage occurs regardless of criminal history, credit or past evictions.'),
('housing-reign-hope-reentry','population_focus.reentry','official_website','confirmed','https://reignofhope.org/','Reign of Hope Inc','Official site labels the service Second Chance Housing and Reentry Housing.'),
('housing-reign-hope-reentry','accepts_violent_offense','official_website','not_eligible','https://reignofhope.org/','Reign of Hope Inc','Official Reentry Housing description limits the program to non-violent offenders.'),
('housing-open-homes-regeneration','population_focus.reentry','official_website','confirmed','https://openhomesfellowship.org/intake/','Open Homes Fellowship','Official intake page has a pre-release procedure for incarcerated applicants.'),
('housing-operation-new-hope-orlando','population_focus.reentry','official_website','confirmed','https://operationnewhope.org/ready4work-orlando/','Operation New Hope','Official Orlando program serves justice-involved people and lists transitional housing support.'),
('housing-lords-place-reentry-navigation','resource_type','official_website','confirmed','https://thelordsplace.org/what-we-do/reentry-program/','The Lord''s Place','Provider explicitly says Reentry is not internal housing, supporting housing_navigation.'),
('housing-riverside-house-rrc','requires_referral','official_website','confirmed','https://riversidehouse.org/get-help/faq/','Riverside House','Residential placement is through BOP/authorized federal partners; public/family placement cannot be initiated directly.'),
('housing-banyan-rrc-miami','population_focus.reentry','official_website','confirmed','https://banyanhealth.org/behavioral-health/adult-psychiatric/behavioral-health-centers/','Banyan Community Health','Official page describes a Residential Reentry Center for people nearing release.'),
('housing-banyan-rrc-miami','requires_referral','federal_directory','confirmed','https://www2.fed.bop.gov/business/rrc_directory.jsp','Federal Bureau of Prisons','Federal RRC directory lists Banyan Community Health Center in Miami.'),
('housing-restoration-destination-reentry','population_focus.reentry','official_website','confirmed','https://restorationdestination.org/prison-reentry-housing/','Restoration Destination','Official provider page offers transitional and permanent shared housing for returning citizens.'),
('housing-restoration-destination-reentry','accepts_sex_offense','211_directory','confirmed','https://211pbtc.myresourcedirectory.com/index.php?all=veterans&id=4947960&option=com_cpx&search_history_id=268672500&task=resource.view','211 Palm Beach/Treasure Coast','Record updated 2026-04-29 states the agency is compliant with state/county guidelines to house sex offenders.'),
('housing-fern-house-reentry-recovery','population_focus.reentry','official_website','confirmed','https://fernhouse.org/mission/','Fern House Inc','Official page says Fern House serves formerly incarcerated men in residential recovery.')
)
INSERT INTO resource_evidence(resource_id,claim_field,method,outcome,source_url,source_name,checked_at,checked_by,notes)
SELECT r.id,ev.claim_field,ev.method,ev.outcome,ev.source_url,ev.source_name,now(),'StreetRise migration 061',ev.notes
FROM ev JOIN resources r ON r.external_id=ev.external_id
WHERE NOT EXISTS (
 SELECT 1 FROM resource_evidence e
 WHERE e.resource_id=r.id AND e.claim_field IS NOT DISTINCT FROM ev.claim_field
   AND e.source_url IS NOT DISTINCT FROM ev.source_url
);
